name: Auth
run-name: "${{ github.actor }} ran ${{ github.workflow }} on ${{ github.ref_name }}"
on:
  push:
    branches:
      - development
    paths:
      - "src/auth/**"
  pull_request:
    branches:
      - main
      - development
    paths:
      - "src/auth/**"
jobs:
  auth:
    runs-on: ubuntu-latest
    if: github.base_ref != 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build -t 'ghcr.io/reviving-hyves/hyves-back-end/auth' -f src/auth/Dockerfile .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
  
      - name: Push Docker Image
        run: docker push ghcr.io/reviving-hyves/hyves-back-end/auth
